deployment:
  tier: backend
  spec:
    replicas: 1

    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "300m"      


service:  
  enabled: true
  servicePort: 80
  podPort: 80
  ingress:
    internal:
      # braces required !!
    - hostname: "{{ .Values.ci.name }}.{{ .Values.ci.namespace }}.k2.env.timo.group"

metrics:
  enabled: false
  servicePort: 80
  podPort: null

